version: '3.9'

services:
  postgraphile:
    build:
      context: .
      dockerfile: Dockerfile.postgraphile
    container_name: ${POSTGRAPHILE_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${POSTGRAPHILE_PORT}:5000"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@matrimony_postgres:5432/${POSTGRES_DB}
      - POSTGRAPHILE_PORT=5000
    networks:
      - matrimony_network

networks:
  matrimony_network:
    external: true
