version: '3.9'

services:
  postgraphile:
    build:
      context: .
      dockerfile: Dockerfile.postgraphile
    container_name: ${POSTGRAPHILE_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${POSTGRAPHILE_PORT}:5000"
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
      POSTGRAPHILE_PORT: "5000"
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - matrimony_network

networks:
  matrimony_network:
    external: true
